### ISSUE TITLE
USDE modifications

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#348]
# Summary

We need to explore changing the USDE method.

Issues:
1. Currently, we have the notion of fields that are related to the issue of data loss. Do we need to have a separate list related to fields pertaining to down time, or does it overcomplicate things?
2. We have [this](https://github.com/numaproj/numaplane/issues/330) issue, which shows that the current method of using "excluded fields" has limitations due to the fact that we don't store the Numaflow specs.
3. We are adding labels and annotations to our `PipelineRollout`, `ISBServiceRollout`, and `MonoVertexRollout` which get passed to the child. We probably should have the capability to consider some of them as Progressive/PPND 

- [ ] [USDE for Progressive, Delete/Recreate](https://github.com/numaproj/numaplane/issues/402)
- [x] [USDE: specify "data loss" fields](https://github.com/numaproj/numaplane/issues/407)
- [ ] [USDE: Enable certain Labels and Annotations to be marked for requiring Progressive/PPND](https://github.com/numaproj/numaplane/issues/408)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Can do this in Q2

**Comment by juliev0** [comment]
Derek has added all of the fields he can think of that could be risks for data loss [here](https://docs.google.com/document/d/12OTQZ5mOGmtLliCkf082jL7xTo9K6X3Y3staNyRRy_M/edit?tab=t.0). I think there is a complexity that some fields implicitly include their child fields, and others do not. (Of course, we can always simplify things if necessary and be conservative.)

**Comment by juliev0** [comment]
We don't need the parent issue anymore. I am closing it.
